MODELS: dict[str, dict] = {
    "catherine-4": {
        "name": "Model Catherine 4",
        "type": "2-Storey House",
        "bedrooms": 4,
        "bathrooms": 2,
        "garage": "1-Car Garage",
        "features": ["Kitchen Area", "Living Area", "Dining Area", "Family Area"],
        "image": "catherine/1.jpg",
        "locations": ["Lucena City", "Sariaya"],
        "description": "A spacious two-storey home with four bedrooms and a family area — perfect for families.",
    },
    "bernice-4": {
        "name": "Model Bernice 4",
        "type": "2-Storey House",
        "bedrooms": 4,
        "bathrooms": 2,
        "garage": "1-Car Garage",
        "features": ["Kitchen Area", "Living Area", "Dining Area", "Family Area"],
        "image": "bernice/1.jpg",
        "locations": ["Lucena City", "Sariaya"],
        "description": "A two-storey home with four bedrooms and a family area — ideal for families who value space.",
    },
    "tristen": {
        "name": "Model Tristen",
        "type": "Bungalow",
        "bedrooms": 3,
        "bathrooms": 2,
        "garage": "1-Car Garage",
        "features": ["Kitchen Area", "Living Area", "Dining Area", "Laundry Area"],
        "image": "tristen/1.jpg",
        "locations": ["Lucena City"],
        "description": "A bungalow with three bedrooms and a laundry area — single-level living at its finest.",
    },
    "sophia": {
        "name": "Model Sophia",
        "type": "Bungalow",
        "bedrooms": 4,
        "bathrooms": 2,
        "garage": "1-Car Garage",
        "features": ["Kitchen Area", "Living Area", "Dining Area"],
        "image": "sophia/1.jpg",
        "locations": ["Lucena City"],
        "description": "A spacious four-bedroom bungalow with generous living spaces and no stairs.",
    },
    "margarette-2": {
        "name": "Model Margarette 2",
        "type": "Socialized Housing",
        "bedrooms": 2,
        "bathrooms": 1,
        "garage": None,
        "features": ["Living Area", "Dining Area", "Kitchen Area", "Porch Area"],
        "image": "margarette/1.jpg",
        "locations": ["Lucena City", "Sariaya"],
        "description": "Affordable two-bedroom socialized housing with a porch — perfect for starting families.",
    },
    "claire-2": {
        "name": "Model Claire 2",
        "type": "Socialized Housing",
        "bedrooms": 2,
        "bathrooms": 1,
        "garage": None,
        "features": ["Living Area", "Dining Area", "Kitchen Area", "Porch Area"],
        "image": "claire/1.jpg",
        "locations": ["Sariaya"],
        "description": "Cozy two-bedroom socialized housing with a porch — affordable living for new homeowners.",
    },
    "amelia-3": {
        "name": "Model Amelia 3",
        "type": "Bungalow",
        "bedrooms": 3,
        "bathrooms": 1,
        "garage": "1-Car Garage",
        "features": ["Living Area", "Dining Area", "Kitchen Area"],
        "image": "amelia/1.jpg",
        "locations": ["Lucena City", "Sariaya"],
        "description": "A practical bungalow with three bedrooms and a car garage. Smart living for modern families.",
    },
    "scarlet": {
        "name": "Model Scarlet",
        "type": "Coming Soon",
        "bedrooms": None,
        "bathrooms": None,
        "garage": None,
        "features": [],
        "image": "scarlet/1.jpg",
        "locations": ["Lucena City"],
        "size": "102 sqm",
        "description": "The Scarlet model at Village of St. Jude Lucena City (BLK. 20 LOT 2 — 102 sqm).",
    },
    "lucia": {
        "name": "Model Lucia",
        "type": "Coming Soon",
        "bedrooms": None,
        "bathrooms": None,
        "garage": None,
        "features": [],
        "image": "lucia/1.jpg",
        "locations": ["Sariaya"],
        "size": "100 sqm",
        "description": "The Lucia model at VSJ Sariaya (100 sqm).",
    },
}
