MODELS: dict[str, dict] = {
    "aspen": {
        "name": "Model Aspen",
        "type": "2-Storey House",
        "bedrooms": 4,
        "bathrooms": 2,
        "garage": "1-Car Garage",
        "features": ["Kitchen Area", "Living Area", "Dining Area", "Family Area"],
        "locations": ["North Village", "South Village"],
        "description": "A spacious two-storey home with four bedrooms and a family area, perfect for families.",
    },
    "birch": {
        "name": "Model Birch",
        "type": "2-Storey House",
        "bedrooms": 4,
        "bathrooms": 2,
        "garage": "1-Car Garage",
        "features": ["Kitchen Area", "Living Area", "Dining Area", "Family Area"],
        "locations": ["North Village", "South Village"],
        "description": "A two-storey home with four bedrooms and a family area, ideal for families who value space.",
    },
    "cedar": {
        "name": "Model Cedar",
        "type": "Bungalow",
        "bedrooms": 3,
        "bathrooms": 2,
        "garage": "1-Car Garage",
        "features": ["Kitchen Area", "Living Area", "Dining Area", "Laundry Area"],
        "locations": ["North Village"],
        "description": "A bungalow with three bedrooms and a laundry area, single-level living at its finest.",
    },
    "dogwood": {
        "name": "Model Dogwood",
        "type": "Bungalow",
        "bedrooms": 4,
        "bathrooms": 2,
        "garage": "1-Car Garage",
        "features": ["Kitchen Area", "Living Area", "Dining Area"],
        "locations": ["North Village"],
        "description": "A spacious four-bedroom bungalow with generous living spaces and no stairs.",
    },
    "elm": {
        "name": "Model Elm",
        "type": "Socialized Housing",
        "bedrooms": 2,
        "bathrooms": 1,
        "garage": None,
        "features": ["Living Area", "Dining Area", "Kitchen Area", "Porch Area"],
        "locations": ["North Village", "South Village"],
        "description": "Affordable two-bedroom socialized housing with a porch, perfect for starting families.",
    },
    "fern": {
        "name": "Model Fern",
        "type": "Socialized Housing",
        "bedrooms": 2,
        "bathrooms": 1,
        "garage": None,
        "features": ["Living Area", "Dining Area", "Kitchen Area", "Porch Area"],
        "locations": ["South Village"],
        "description": "Cozy two-bedroom socialized housing with a porch, affordable living for new homeowners.",
    },
    "hazel": {
        "name": "Model Hazel",
        "type": "Bungalow",
        "bedrooms": 3,
        "bathrooms": 1,
        "garage": "1-Car Garage",
        "features": ["Living Area", "Dining Area", "Kitchen Area"],
        "locations": ["North Village", "South Village"],
        "description": "A practical bungalow with three bedrooms and a car garage. Smart living for modern families.",
    },
    "iris": {
        "name": "Model Iris",
        "type": "Coming Soon",
        "bedrooms": None,
        "bathrooms": None,
        "garage": None,
        "features": [],
        "locations": ["North Village"],
        "size": "102 sqm",
        "description": "A coming-soon model on a 102 sqm lot.",
    },
    "juniper": {
        "name": "Model Juniper",
        "type": "Coming Soon",
        "bedrooms": None,
        "bathrooms": None,
        "garage": None,
        "features": [],
        "locations": ["South Village"],
        "size": "100 sqm",
        "description": "A coming-soon model on a 100 sqm lot.",
    },
}
