"""fixup_billing_overhaul

Revision ID: 5eeffdafdd6c
Revises: b2825fc5a8c4
Create Date: 2026-07-06 06:22:13.833868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eeffdafdd6c'
down_revision = 'b2825fc5a8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.alter_column('is_paid',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('receipt_number',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('cashier_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_billings_timestamp'))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_meter_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_index(batch_op.f('ix_customers_customer_number'))
        batch_op.create_index(batch_op.f('ix_customers_customer_number'), ['customer_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_customer_number'))
        batch_op.create_index(batch_op.f('ix_customers_customer_number'), ['customer_number'], unique=False)
        batch_op.drop_column('max_meter_value')

    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=False))
        batch_op.create_index(batch_op.f('ix_billings_timestamp'), ['timestamp'], unique=False)
        batch_op.alter_column('cashier_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('receipt_number',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('is_paid',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
