# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

try:
    from . import billing_pb2 as billing__pb2
except ImportError:
    try:
        import billing_pb2 as billing__pb2
    except ImportError:
        from shared.proto_gen import billing_pb2 as billing__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in billing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BillingServiceStub:
    """BillingService handles customer, billing, payment and reading
    operations for internal container-to-container traffic over gRPC.
    Public HTTP via Caddy handle /api/* remains the external surface;
    internal callers (portals, webhook, worker) should prefer this service
    via grpc.aio.insecure_channel("api:50051").
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCustomer = channel.unary_unary(
                '/api.v1.BillingService/GetCustomer',
                request_serializer=billing__pb2.GetCustomerRequest.SerializeToString,
                response_deserializer=billing__pb2.GetCustomerResponse.FromString,
                _registered_method=True)
        self.ListCustomers = channel.unary_unary(
                '/api.v1.BillingService/ListCustomers',
                request_serializer=billing__pb2.ListCustomersRequest.SerializeToString,
                response_deserializer=billing__pb2.ListCustomersResponse.FromString,
                _registered_method=True)
        self.CreateCustomer = channel.unary_unary(
                '/api.v1.BillingService/CreateCustomer',
                request_serializer=billing__pb2.CreateCustomerRequest.SerializeToString,
                response_deserializer=billing__pb2.CreateCustomerResponse.FromString,
                _registered_method=True)
        self.GetBillingHistory = channel.unary_unary(
                '/api.v1.BillingService/GetBillingHistory',
                request_serializer=billing__pb2.GetBillingHistoryRequest.SerializeToString,
                response_deserializer=billing__pb2.GetBillingHistoryResponse.FromString,
                _registered_method=True)
        self.SubmitPayment = channel.unary_unary(
                '/api.v1.BillingService/SubmitPayment',
                request_serializer=billing__pb2.SubmitPaymentRequest.SerializeToString,
                response_deserializer=billing__pb2.SubmitPaymentResponse.FromString,
                _registered_method=True)
        self.GetReadings = channel.unary_unary(
                '/api.v1.BillingService/GetReadings',
                request_serializer=billing__pb2.GetReadingsRequest.SerializeToString,
                response_deserializer=billing__pb2.GetReadingsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/api.v1.BillingService/HealthCheck',
                request_serializer=billing__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=billing__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class BillingServiceServicer:
    """BillingService handles customer, billing, payment and reading
    operations for internal container-to-container traffic over gRPC.
    Public HTTP via Caddy handle /api/* remains the external surface;
    internal callers (portals, webhook, worker) should prefer this service
    via grpc.aio.insecure_channel("api:50051").
    """

    def GetCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCustomers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBillingHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReadings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomer,
                    request_deserializer=billing__pb2.GetCustomerRequest.FromString,
                    response_serializer=billing__pb2.GetCustomerResponse.SerializeToString,
            ),
            'ListCustomers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCustomers,
                    request_deserializer=billing__pb2.ListCustomersRequest.FromString,
                    response_serializer=billing__pb2.ListCustomersResponse.SerializeToString,
            ),
            'CreateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomer,
                    request_deserializer=billing__pb2.CreateCustomerRequest.FromString,
                    response_serializer=billing__pb2.CreateCustomerResponse.SerializeToString,
            ),
            'GetBillingHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBillingHistory,
                    request_deserializer=billing__pb2.GetBillingHistoryRequest.FromString,
                    response_serializer=billing__pb2.GetBillingHistoryResponse.SerializeToString,
            ),
            'SubmitPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitPayment,
                    request_deserializer=billing__pb2.SubmitPaymentRequest.FromString,
                    response_serializer=billing__pb2.SubmitPaymentResponse.SerializeToString,
            ),
            'GetReadings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReadings,
                    request_deserializer=billing__pb2.GetReadingsRequest.FromString,
                    response_serializer=billing__pb2.GetReadingsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=billing__pb2.HealthCheckRequest.FromString,
                    response_serializer=billing__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.v1.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService:
    """BillingService handles customer, billing, payment and reading
    operations for internal container-to-container traffic over gRPC.
    Public HTTP via Caddy handle /api/* remains the external surface;
    internal callers (portals, webhook, worker) should prefer this service
    via grpc.aio.insecure_channel("api:50051").
    """

    @staticmethod
    def GetCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.BillingService/GetCustomer',
            billing__pb2.GetCustomerRequest.SerializeToString,
            billing__pb2.GetCustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCustomers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.BillingService/ListCustomers',
            billing__pb2.ListCustomersRequest.SerializeToString,
            billing__pb2.ListCustomersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.BillingService/CreateCustomer',
            billing__pb2.CreateCustomerRequest.SerializeToString,
            billing__pb2.CreateCustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBillingHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.BillingService/GetBillingHistory',
            billing__pb2.GetBillingHistoryRequest.SerializeToString,
            billing__pb2.GetBillingHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.BillingService/SubmitPayment',
            billing__pb2.SubmitPaymentRequest.SerializeToString,
            billing__pb2.SubmitPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReadings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.BillingService/GetReadings',
            billing__pb2.GetReadingsRequest.SerializeToString,
            billing__pb2.GetReadingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.BillingService/HealthCheck',
            billing__pb2.HealthCheckRequest.SerializeToString,
            billing__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CustomerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCustomer = channel.unary_unary(
                '/api.v1.CustomerService/GetCustomer',
                request_serializer=billing__pb2.GetCustomerRequest.SerializeToString,
                response_deserializer=billing__pb2.GetCustomerResponse.FromString,
                _registered_method=True)
        self.CreateCustomer = channel.unary_unary(
                '/api.v1.CustomerService/CreateCustomer',
                request_serializer=billing__pb2.CreateCustomerRequest.SerializeToString,
                response_deserializer=billing__pb2.CreateCustomerResponse.FromString,
                _registered_method=True)


class CustomerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomer,
                    request_deserializer=billing__pb2.GetCustomerRequest.FromString,
                    response_serializer=billing__pb2.GetCustomerResponse.SerializeToString,
            ),
            'CreateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomer,
                    request_deserializer=billing__pb2.CreateCustomerRequest.FromString,
                    response_serializer=billing__pb2.CreateCustomerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.v1.CustomerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.CustomerService/GetCustomer',
            billing__pb2.GetCustomerRequest.SerializeToString,
            billing__pb2.GetCustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.v1.CustomerService/CreateCustomer',
            billing__pb2.CreateCustomerRequest.SerializeToString,
            billing__pb2.CreateCustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
